// petdex extension for OMP (Oh My Pi). Auto-generated by the Petdex
// desktop app's Agents panel.
//
// OMP has no shell-command hooks: its docs call that subsystem legacy and
// point at an in-process extension API instead, so this is a module OMP
// loads rather than a config file we edit. Everything below is typed
// against packages/coding-agent/src/extensibility/extensions/types.ts at
// can1357/oh-my-pi.
//
// Each pi.on handler below maps one OMP event to one mascot state; edit
// the state strings there to change what the pet does.

import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

const SIDECAR_URL = "http://127.0.0.1:7777/state";
const SIDECAR_BUBBLE_URL = "http://127.0.0.1:7777/bubble";
const RUNTIME_DIR = join(homedir(), ".petdex", "runtime");
const TOKEN_PATH = join(RUNTIME_DIR, "update-token");
const KILLSWITCH_PATH = join(RUNTIME_DIR, "hooks-disabled");
const AGENT_SOURCE = "omp";

// Read-only tools read as thinking rather than working, matching how the
// other adapters split `review` from `running`.
const REVIEW_TOOLS = new Set(["read", "grep", "glob", "list", "search"]);

async function readToken(): Promise<string | null> {
  try {
    return (await readFile(TOKEN_PATH, "utf8")).trim();
  } catch {
    return null;
  }
}

async function postJson(
  url: string,
  body: Record<string, unknown>,
  token: string,
): Promise<void> {
  try {
    await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Petdex-Update-Token": token,
      },
      body: JSON.stringify(body),
      // 300ms instead of 1s: well above any real localhost roundtrip and
      // below the threshold an agent user notices as latency. Extensions
      // share OMP's process, so a hung request would stall the agent.
      signal: AbortSignal.timeout(300),
    });
  } catch {
    // sidecar offline: stay quiet, the agent shouldn't notice.
  }
}

type Notify = {
  state: string;
  duration?: number;
  text?: string;
  title?: string;
  busy?: boolean;
};

async function notify({
  state,
  duration,
  text,
  title,
  busy,
}: Notify): Promise<void> {
  // Killswitch first, before the token read, so the disabled state costs
  // one existsSync and nothing else.
  if (existsSync(KILLSWITCH_PATH)) return;
  const token = await readToken();
  if (!token) return; // sidecar offline or missing — silently no-op
  const stateBody: Record<string, unknown> =
    duration != null
      ? { state, duration, agent_source: AGENT_SOURCE }
      : { state, agent_source: AGENT_SOURCE };
  const bubbleBody: Record<string, unknown> = {
    text,
    agent_source: AGENT_SOURCE,
  };
  if (title) bubbleBody.title = title;
  if (busy !== undefined) bubbleBody.busy = busy;
  await Promise.all([
    postJson(SIDECAR_URL, stateBody, token),
    text ? postJson(SIDECAR_BUBBLE_URL, bubbleBody, token) : Promise.resolve(),
  ]);
}

function clip(value: string, max: number): string {
  const flat = value.replace(/\s+/g, " ").trim();
  return flat.length > max ? `${flat.slice(0, max - 1)}…` : flat;
}

/** A short label for what a tool call is doing, for the bubble text. */
function describeTool(
  toolName: string,
  input: Record<string, unknown>,
  done: boolean,
): string {
  const field = (key: string): string | null => {
    const value = input?.[key];
    return typeof value === "string" && value.length > 0 ? value : null;
  };
  switch (toolName) {
    case "bash": {
      const command = field("command");
      return command
        ? `${done ? "Ran" : "Running"} ${clip(command, 28)}`
        : done
          ? "Ran a command"
          : "Running a command";
    }
    case "read":
      return `${done ? "Read" : "Reading"} ${clip(field("file_path") ?? field("path") ?? "a file", 28)}`;
    case "write":
    case "edit":
      return `${done ? "Edited" : "Editing"} ${clip(field("file_path") ?? field("path") ?? "a file", 28)}`;
    case "grep": {
      const pattern = field("pattern");
      // Typographic quotes, not ASCII: the sidecar reads the bubble body
      // back with a scanner that stops at a bare quote (#628).
      return pattern
        ? `${done ? "Searched" : "Searching"} “${clip(pattern, 24)}”`
        : done
          ? "Searched files"
          : "Searching files";
    }
    default:
      return `${done ? "Ran" : "Running"} ${clip(toolName, 28)}`;
  }
}

// Minimal structural types. Importing OMP's own would couple the
// generated file to a package path that varies by install, and these are
// the only fields read. Kept in sync with
// packages/coding-agent/src/extensibility/extensions/types.ts.
type ToolCallEvent = { toolName: string; input?: Record<string, unknown> };
type ToolResultEvent = {
  toolName: string;
  input?: Record<string, unknown>;
  isError: boolean;
};
type InputEvent = { text: string };

type ExtensionAPI = {
  on(event: string, handler: (event: never, ctx: never) => unknown): void;
  registerCommand(
    name: string,
    options: {
      description?: string;
      handler: (
        args: string,
        ctx: { ui: { notify(message: string, type?: string): void } },
      ) => Promise<void>;
    },
  ): void;
};

export default function petdex(pi: ExtensionAPI): void {
  let lastPrompt: string | null = null;

  pi.on("session_start", (async () => {
    await notify({ state: "jumping", duration: 1200, busy: false });
  }) as never);

  pi.on("input", (async (event: InputEvent) => {
    // `text` is a plain string here, unlike Kimi Code's ContentPart[].
    lastPrompt = typeof event?.text === "string" ? clip(event.text, 60) : null;
    await notify({ state: "jumping", duration: 900, busy: false });
  }) as never);

  pi.on("tool_call", (async (event: ToolCallEvent) => {
    const name = event?.toolName ?? "";
    await notify({
      state: REVIEW_TOOLS.has(name) ? "review" : "running",
      text: describeTool(name, event?.input ?? {}, false),
      title: lastPrompt ?? undefined,
      busy: true,
    });
  }) as never);

  pi.on("tool_result", (async (event: ToolResultEvent) => {
    // `isError` is on the payload, set true before the error is rethrown,
    // so failure is a real signal here rather than something inferred
    // from result text the way CodeBuddy forces.
    if (event?.isError) {
      await notify({
        state: "failed",
        duration: 2500,
        text: `${describeTool(event?.toolName ?? "", event?.input ?? {}, true)} failed`,
        title: lastPrompt ?? undefined,
        busy: false,
      });
      return;
    }
    await notify({
      state: "idle",
      text: describeTool(event?.toolName ?? "", event?.input ?? {}, true),
      title: lastPrompt ?? undefined,
      busy: true,
    });
  }) as never);

  pi.on("tool_approval_requested", (async () => {
    await notify({
      state: "waiting",
      text: "Waiting on you.",
      title: lastPrompt ?? undefined,
      busy: false,
    });
  }) as never);

  pi.on("agent_end", (async () => {
    await notify({
      state: "waving",
      duration: 1500,
      text: "Done.",
      title: lastPrompt ?? undefined,
      busy: false,
    });
  }) as never);

  pi.on("session_shutdown", (async () => {
    await notify({ state: "idle", busy: false });
  }) as never);

  pi.registerCommand("petdex", {
    description: "Show whether the Petdex mascot is connected",
    handler: async (_args, ctx) => {
      if (existsSync(KILLSWITCH_PATH)) {
        ctx.ui.notify("Petdex hooks are disabled (killswitch on).", "warning");
        return;
      }
      const token = await readToken();
      ctx.ui.notify(
        token
          ? "Petdex is connected."
          : "Petdex desktop is not running (no sidecar token).",
        token ? "info" : "warning",
      );
    },
  });
}
